### ISSUE TITLE
Please add MIT-LICENSE to the gemspec

### ISSUE THREAD

**Issue by dlitz** [dadooda/smart_tuple#1]
The GitHub repository for this project includes an MIT-LICENSE file, which requires that the copyright notice and permission notices are distributed with the code. Unfortunately, the way the gemspec is written means that everyone who distributes the .gem file automatically violates the license by not including the copyright and the permission notice with the code. :)

Please update smart_tuple.gemspec to include the MIT-LICENSE in s.files.  A statement in the README that smart_tuple is actually covered by that license would be nice, too. :)

**Comment by dadooda** [comment]
Yes you're right. Thanks for the note. I'll fix it right away.

**Comment by dadooda** [comment]
Dwayne

Pushed the fix to repo. Is it better now? Please advise.

**Comment by dlitz** [comment]
Cool, it looks good.  I noticed that "gem build smart_tuple.gemspec" fails without getting Jeweler and running "rake gemspec", but when that happens, it looks good.

Thanks for the quick response!
